version: '2'
services:
  computer-service:
      image: afayes/computer-service
      container_name: computer-service
      ports:
        - "8080:8080"
      environment:
        ALLOWEDORIGINS: "http://localhost"
  computer-ui:
      image: afayes/computer-ui
      container_name: computer-ui
      ports:
        - "80:80"


